INSERT INTO cities(id,name,state) VALUES (35,'São Paulo','SP');
INSERT INTO cities(id,name,state) VALUES (41,'Paraná','PR');
INSERT INTO cities(id,name,state) VALUES (42,'Santa Catarina','SC');
INSERT INTO cities(id,name,state) VALUES (43,'Rio Grande do Sul','RS');
INSERT INTO cities(id,name,state) VALUES (50,'Mato Grosso do Sul','MS');
INSERT INTO cities(id,name,state) VALUES (11,'Rondônia','RO');
INSERT INTO cities(id,name,state) VALUES (12,'Acre','AC');
INSERT INTO cities(id,name,state) VALUES (13,'Amazonas','AM');
INSERT INTO cities(id,name,state) VALUES (14,'Roraima','RR');
INSERT INTO cities(id,name,state) VALUES (15,'Pará','PA');
INSERT INTO cities(id,name,state) VALUES (16,'Amapá','AP');
INSERT INTO cities(id,name,state) VALUES (17,'Tocantins','TO');
INSERT INTO cities(id,name,state) VALUES (21,'Maranhão','MA');
INSERT INTO cities(id,name,state) VALUES (24,'Rio Grande do Norte','RN');
INSERT INTO cities(id,name,state) VALUES (25,'Paraíba','PB');
INSERT INTO cities(id,name,state) VALUES (26,'Pernambuco','PE');
INSERT INTO cities(id,name,state) VALUES (27,'Alagoas','AL');
INSERT INTO cities(id,name,state) VALUES (28,'Sergipe','SE');
INSERT INTO cities(id,name,state) VALUES (29,'Bahia','BA');
INSERT INTO cities(id,name,state) VALUES (31,'Minas Gerais','MG');
INSERT INTO cities(id,name,state) VALUES (33,'Rio de Janeiro','RJ');
INSERT INTO cities(id,name,state) VALUES (51,'Mato Grosso','MT');
INSERT INTO cities(id,name,state) VALUES (52,'Goiás','GO');
INSERT INTO cities(id,name,state) VALUES (53,'Distrito Federal','DF');
INSERT INTO cities(id,name,state) VALUES (22,'Piauí','PI');
INSERT INTO cities(id,name,state) VALUES (23,'Ceará','CE');
INSERT INTO cities(id,name,state) VALUES (32,'Espírito Santo','ES');
